project_id = "hr-masterdata"

[api]
port = 15421
schemas = ["public"]

[db]
port = 15422
shadow_port = 15420

[studio]
port = 15423

[inbucket]
port = 15424
smtp_port = 15425
pop3_port = 15426

[analytics]
port = 15427
