/**
 * Utility function to auto-populate PE3 date description
 * Extracted for testability
 * 
 * @param dateValue - Date value in YYYY-MM-DD format
 * @param timeValue - Time value in HH:mm format
 * @returns Formatted description in Swedish locale format (e.g., "15 mars 2025 14:30")
 */
export function formatPE3Description(dateValue: string, timeValue: string): string | null {
  if (!dateValue || !timeValue || timeValue.trim() === '') {
    return null;
  }

  try {
    const date = new Date(dateValue + 'T00:00:00');
    if (isNaN(date.getTime())) {
      return null; // Invalid date
    }
    
    const day = date.getDate();
    const months = ['januari', 'februari', 'mars', 'april', 'maj', 'juni', 'juli', 'augusti', 'september', 'oktober', 'november', 'december'];
    const month = months[date.getMonth()];
    const year = date.getFullYear();
    const formattedTime = timeValue.trim();
    
    // Format: "15 mars 2025 14:30"
    return `${day} ${month} ${year} ${formattedTime}`;
  } catch (error) {
    // Invalid date, skip auto-population
    console.warn('Failed to format PE3 description:', error);
    return null;
  }
}

/**
 * Check if a description matches the auto-generated pattern
 * Used to determine if description can be auto-updated
 */
export function isAutoGeneratedDescription(description: string | null | undefined): boolean {
  if (!description) return true; // Empty descriptions can be auto-updated
  const previousAutoPattern = /^\d{1,2} \w+ \d{4} \d{2}:\d{2}$/;
  return previousAutoPattern.test(description);
}

