/* eslint-disable @typescript-eslint/no-explicit-any */
import { type UseFormReturn } from "react-hook-form";
import { getWeekNumberFromDateString } from "@/lib/utils/date-utils";
import {
  formatPE3Description,
  isAutoGeneratedDescription,
} from "@/lib/utils/pe3-description-formatter";
import { formatOMCDateDescription } from "@/lib/utils/omc-date-formatter";

const SWEDISH_WEEKDAYS = [
  "Söndag",
  "Måndag",
  "Tisdag",
  "Onsdag",
  "Torsdag",
  "Fredag",
  "Lördag",
];

/**
 * Generates a Swedish weekday description for a date (e.g., "Fredag 14/2").
 * Used for Stena Dates and Other category dates.
 */
export function generateSwedishDateDescription(
  dateValue: string
): string | null {
  try {
    const date = new Date(dateValue + "T00:00:00");
    if (isNaN(date.getTime())) return null;
    const weekday = SWEDISH_WEEKDAYS[date.getDay()];
    const day = date.getDate();
    const month = date.getMonth() + 1;
    return `${weekday} ${day}/${month}`;
  } catch {
    return null;
  }
}

/**
 * Handles all auto-populate side effects when a date value changes:
 * week number calculation + description generation based on category.
 * Called from both onChange and onPaste handlers in the date field.
 */
export function handleDateValueAutoPopulate(
  form: UseFormReturn<any>,
  newDateValue: string
) {
  const weekNum = getWeekNumberFromDateString(newDateValue);
  if (weekNum !== null) {
    form.setValue("week_number", weekNum);
  }

  if (!newDateValue) return;

  const category = form.getValues("category");

  if (category === "ÖMC Dates") {
    const description = formatOMCDateDescription(newDateValue);
    if (description) {
      form.setValue("date_description", description);
    }
  } else if (category === "PE3 Dates") {
    triggerPE3DescriptionUpdate(form, newDateValue);
  } else {
    const description = generateSwedishDateDescription(newDateValue);
    if (description) {
      form.setValue("date_description", description);
    }
  }
}

/**
 * Deferred PE3 description update — runs in a setTimeout to ensure
 * form state is settled before reading cross-field values.
 */
export function triggerPE3DescriptionUpdate(
  form: UseFormReturn<any>,
  dateValue?: string,
  timeValue?: string | null
) {
  setTimeout(() => {
    const resolvedDate = dateValue ?? form.getValues("date_value");
    const resolvedTime = timeValue ?? form.getValues("time_value");
    const currentDescription = form.getValues("date_description");

    if (resolvedDate && resolvedTime) {
      const autoDescription = formatPE3Description(resolvedDate, resolvedTime);
      if (
        autoDescription &&
        (!currentDescription ||
          isAutoGeneratedDescription(currentDescription))
      ) {
        form.setValue("date_description", autoDescription, {
          shouldDirty: false,
        });
      }
    }
  }, 0);
}
