/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useRef } from "react";
import { type UseFormReturn } from "react-hook-form";
import { getWeekNumberFromDateString } from "@/lib/utils/date-utils";
import {
  formatPE3Description,
  isAutoGeneratedDescription,
} from "@/lib/utils/pe3-description-formatter";
import { formatOMCDateDescription } from "@/lib/utils/omc-date-formatter";
import { calculatePE3Deadlines } from "@/lib/services/pe3-deadline-calculator";
import { generateSwedishDateDescription } from "@/components/dashboard/important-date-form/date-change-helpers";

/**
 * Manages cross-field auto-population effects for the important date form:
 * - Updates date/description when year changes
 * - Auto-generates PE3 descriptions from date + time
 * - Auto-calculates PE3 deadlines from date
 */
export function useImportantDateAutoPopulate(
  form: UseFormReturn<any>,
  isOpen: boolean
) {
  const prevYearRef = useRef(0);

  const category = form.watch("category");
  const dateValue = form.watch("date_value");
  const timeValue = form.watch("time_value");
  const year = form.watch("year");

  // Update date_value when year changes (if date is already set)
  useEffect(() => {
    if (!isOpen || !dateValue) return;

    const currentYear = form.getValues("year");
    const prevYear = prevYearRef.current;

    if (
      prevYear !== 0 &&
      prevYear !== currentYear &&
      typeof currentYear === "number" &&
      !isNaN(currentYear) &&
      typeof prevYear === "number" &&
      !isNaN(prevYear)
    ) {
      try {
        const dateMatch = dateValue.match(/^(\d{4})-(\d{2})-(\d{2})$/);
        if (dateMatch) {
          const [, , month, day] = dateMatch;
          const updatedDate = `${currentYear}-${month}-${day}`;
          form.setValue("date_value", updatedDate, { shouldDirty: false });

          const weekNum = getWeekNumberFromDateString(updatedDate);
          if (weekNum !== null) {
            form.setValue("week_number", weekNum, { shouldDirty: false });
          }

          const currentCategory = form.getValues("category");
          if (currentCategory === "ÖMC Dates") {
            const description = formatOMCDateDescription(updatedDate);
            if (description) {
              form.setValue("date_description", description, {
                shouldDirty: false,
              });
            }
          } else if (currentCategory === "PE3 Dates") {
            const currentTimeValue = form.getValues("time_value");
            if (currentTimeValue) {
              const autoDescription = formatPE3Description(
                updatedDate,
                currentTimeValue
              );
              const currentDescription = form.getValues("date_description");
              if (
                autoDescription &&
                (!currentDescription ||
                  isAutoGeneratedDescription(currentDescription))
              ) {
                form.setValue("date_description", autoDescription, {
                  shouldDirty: false,
                });
              }
            }
          } else {
            const description = generateSwedishDateDescription(updatedDate);
            if (description) {
              form.setValue("date_description", description, {
                shouldDirty: false,
              });
            }
          }
        }
      } catch (error) {
        console.error("Error updating date for year change:", error);
      }
    }

    prevYearRef.current = currentYear;
  }, [year, dateValue, isOpen, form]);

  // Auto-populate description for PE3 dates when date/time/category changes
  useEffect(() => {
    if (!isOpen) return;

    const currentCategory = form.getValues("category");
    const currentDateValue = form.getValues("date_value");
    const currentTimeValue = form.getValues("time_value");
    const currentDescription = form.getValues("date_description");

    if (
      currentCategory === "PE3 Dates" &&
      currentDateValue &&
      currentTimeValue
    ) {
      const autoDescription = formatPE3Description(
        currentDateValue,
        currentTimeValue
      );
      if (
        autoDescription &&
        (!currentDescription ||
          isAutoGeneratedDescription(currentDescription))
      ) {
        form.setValue("date_description", autoDescription, {
          shouldDirty: false,
        });
      }
    }
  }, [category, dateValue, timeValue, isOpen, form]);

  // Auto-calculate deadlines for PE3 dates when date is set
  useEffect(() => {
    if (!isOpen) return;

    const currentCategory = form.getValues("category");
    const currentDateValue = form.getValues("date_value");
    const currentDeadlineSubmit = form.getValues("deadline_submit");
    const currentDeadlineCancel = form.getValues("deadline_cancel");

    if (
      currentCategory === "PE3 Dates" &&
      currentDateValue &&
      !currentDeadlineSubmit &&
      !currentDeadlineCancel
    ) {
      try {
        const calculation = calculatePE3Deadlines([currentDateValue]);
        form.setValue("deadline_submit", calculation.deadlineSubmit, {
          shouldDirty: false,
        });
        form.setValue("deadline_cancel", calculation.deadlineCancel, {
          shouldDirty: false,
        });
      } catch (error) {
        console.error("Error calculating PE3 deadlines:", error);
      }
    }
  }, [category, dateValue, isOpen, form]);
}
