-- Schema-only capture. It returns definitions to the in-memory collector only.
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL statement_timeout = '20s';
SET LOCAL lock_timeout = '3s';
SET LOCAL idle_in_transaction_session_timeout = '30s';
SELECT jsonb_build_object(
  'schema_version',1,
  'scope','schema_only',
  'public_schema_acl',(SELECT to_jsonb(n.nspacl) FROM pg_namespace n WHERE n.nspname='public'),
  'unsupported_function_kind_count',(SELECT count(*)::int FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind<>'f'),
  'tables',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'options',c.reloptions,'partition_strategy',(SELECT partstrat::text FROM pg_partitioned_table pt WHERE pt.partrelid=c.oid),'acl',c.relacl,'definition',(CASE WHEN c.relkind='v' THEN pg_get_viewdef(c.oid,true) ELSE NULL END)) ORDER BY n.nspname,c.relname),'[]'::jsonb) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p','v')),
  'columns',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'attnum',a.attnum,'nullable',NOT a.attnotnull,'identity',a.attidentity::text,'generated',a.attgenerated::text,'collation',(CASE WHEN a.attcollation=0 THEN NULL ELSE a.attcollation::regcollation::text END),'acl',a.attacl,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY c.relname,a.attnum),'[]'::jsonb) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE n.nspname='public' AND c.relkind IN ('r','p') AND a.attnum>0 AND NOT a.attisdropped),
  'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',x.conname,'type',x.contype::text,'validated',x.convalidated,'deferrable',x.condeferrable,'initially_deferred',x.condeferred,'no_inherit',x.connoinherit,'definition',pg_get_constraintdef(x.oid,true)) ORDER BY c.relname,x.conname),'[]'::jsonb) FROM pg_constraint x JOIN pg_class c ON c.oid=x.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'),
  'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',i.relname,'valid',x.indisvalid,'ready',x.indisready,'unique',x.indisunique,'primary',x.indisprimary,'immediate',x.indimmediate,'is_constraint',(EXISTS(SELECT 1 FROM pg_constraint con WHERE con.conindid=i.oid)),'definition',pg_get_indexdef(i.oid)) ORDER BY c.relname,i.relname),'[]'::jsonb) FROM pg_index x JOIN pg_class c ON c.oid=x.indrelid JOIN pg_class i ON i.oid=x.indexrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'),
  'policies',(SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.tablename,p.policyname),'[]'::jsonb) FROM pg_policies p WHERE p.schemaname='public'),
  'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'volatility',p.provolatile::text,'strict',p.proisstrict,'security_definer',p.prosecdef,'parallel',p.proparallel::text,'leakproof',p.proleakproof,'definition',pg_get_functiondef(p.oid),'acl',p.proacl,'settings',p.proconfig) ORDER BY p.oid::regprocedure::text),'[]'::jsonb) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f'),
  'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'enabled',t.tgenabled::text,'constraint_trigger',(t.tgconstraint<>0),'deferrable',t.tgdeferrable,'initially_deferred',t.tginitdeferred,'function_signature',t.tgfoid::regprocedure::text,'definition',pg_get_triggerdef(t.oid,true)) ORDER BY c.relname,t.tgname),'[]'::jsonb) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND NOT t.tgisinternal),
  'types',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',t.typname,'owner',pg_get_userbyid(t.typowner),'type_kind',t.typtype,'definition',pg_catalog.format_type(t.oid,NULL),'acl',t.typacl,'enum_labels',(SELECT coalesce(jsonb_agg(e.enumlabel ORDER BY e.enumsortorder),'[]'::jsonb) FROM pg_enum e WHERE e.enumtypid=t.oid),'domain_base_type',(CASE WHEN t.typtype='d' THEN format_type(t.typbasetype,t.typtypmod) ELSE NULL END)) ORDER BY t.typname),'[]'::jsonb) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public'),
  'sequences',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl,'data_type',format_type(s.seqtypid,NULL),'start_value',s.seqstart::text,'increment_by',s.seqincrement::text,'min_value',s.seqmin::text,'max_value',s.seqmax::text,'cache_size',s.seqcache::text,'cycle',s.seqcycle,'owned_by',(SELECT format('%I.%I.%I',owner_ns.nspname,owner_table.relname,owner_column.attname) FROM pg_depend d JOIN pg_class owner_table ON owner_table.oid=d.refobjid JOIN pg_namespace owner_ns ON owner_ns.oid=owner_table.relnamespace JOIN pg_attribute owner_column ON owner_column.attrelid=owner_table.oid AND owner_column.attnum=d.refobjsubid WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.deptype='a' LIMIT 1)) ORDER BY c.relname),'[]'::jsonb) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_sequence s ON s.seqrelid=c.oid WHERE n.nspname='public' AND c.relkind='S'),
  'auth_users_schema',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'attnum',a.attnum,'nullable',NOT a.attnotnull,'identity',a.attidentity::text,'generated',a.attgenerated::text,'collation',(CASE WHEN a.attcollation=0 THEN NULL ELSE a.attcollation::regcollation::text END),'acl',a.attacl,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum),'[]'::jsonb) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='auth.users'::regclass AND a.attname='id' AND a.attnum>0 AND NOT a.attisdropped)
) AS schema_capture;
ROLLBACK;
