"use client";

import { useState, useEffect, useRef } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import { useTranslations } from "@/lib/i18n";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { createImportantDateSchema } from "@/lib/validation/important-date-schema";
import { importantDateService } from "@/lib/services/important-date-service";
import { getWeekNumberFromDateString } from "@/lib/utils/date-utils";
import { formatPE3Description, isAutoGeneratedDescription } from "@/lib/utils/pe3-description-formatter";
import { formatOMCDateDescription } from "@/lib/utils/omc-date-formatter";
import { calculatePE3Deadlines } from "@/lib/services/pe3-deadline-calculator";
import { OMCDatePicker } from "./omc-date-picker";
import { TimePicker } from "./time-picker";
import { z } from "zod";

type CreateImportantDateInput = z.infer<typeof createImportantDateSchema>;

interface AddImportantDateModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export function AddImportantDateModal({
  isOpen,
  onClose,
  onSuccess,
}: AddImportantDateModalProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const prevIsOpenRef = useRef(false);
  
  const t = useTranslations('modals');
  const tCommon = useTranslations('common');

  const form = useForm<CreateImportantDateInput>({
    resolver: zodResolver(createImportantDateSchema),
    defaultValues: {
      week_number: null,
      year: new Date().getFullYear(),
      category: "Stena Dates",
      date_description: "",
      date_value: "",
      time_value: null,
      deadline_submit: null,
      deadline_cancel: null,
      notes: null,
      max_spots: 0, // Will be set by schema transform based on category
      remaining_spots: 0, // Will be set by schema transform based on category
    },
  });

  // Reset form when modal transitions from closed to open
  useEffect(() => {
    if (isOpen && !prevIsOpenRef.current) {
      form.reset({
        week_number: null,
        year: new Date().getFullYear(),
        category: "Stena Dates",
        date_description: "",
        date_value: "",
        time_value: null,
        deadline_submit: null,
        deadline_cancel: null,
        notes: null,
      });
    }
    prevIsOpenRef.current = isOpen;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  // Auto-populate description for PE3 dates with Swedish locale format
  // Use polling approach that works in both production and tests (form.watch() unreliable in JSDOM)
  const category = form.watch('category');
  const dateValue = form.watch('date_value');
  const timeValue = form.watch('time_value');
  const year = form.watch('year');
  
  // Track previous values to detect changes
  const prevValuesRef = useRef({ category: '', dateValue: '', timeValue: '', year: 0 });
  
  // Update date_value when year changes (if date is already set)
  useEffect(() => {
    if (!isOpen || !dateValue) return;

    const currentYear = form.getValues('year');
    const prevYear = prevValuesRef.current.year;

    // If year changed and date_value is set, and both years are valid numbers, update the date to use the new year
    if (prevYear !== 0 && prevYear !== currentYear && dateValue && 
        typeof currentYear === 'number' && !isNaN(currentYear) && 
        typeof prevYear === 'number' && !isNaN(prevYear)) {
      try {
        // Parse the current date (ISO format: YYYY-MM-DD)
        const dateMatch = dateValue.match(/^(\d{4})-(\d{2})-(\d{2})$/);
        if (dateMatch) {
          const [, , month, day] = dateMatch;
          // Update date_value with new year, keeping same month and day
          const updatedDate = `${currentYear}-${month}-${day}`;
          form.setValue('date_value', updatedDate, { shouldDirty: false });
          
          // Recalculate week number if date was updated
          const weekNum = getWeekNumberFromDateString(updatedDate);
          if (weekNum !== null) {
            form.setValue('week_number', weekNum, { shouldDirty: false });
          }

          // Update description for non-PE3 dates
          const currentCategory = form.getValues('category');
          if (currentCategory !== 'PE3 Dates') {
            const date = new Date(updatedDate + 'T00:00:00');
            const weekdays = ['Söndag', 'Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag'];
            const weekday = weekdays[date.getDay()];
            const dayNum = date.getDate();
            const monthNum = date.getMonth() + 1;
            const description = `${weekday} ${dayNum}/${monthNum}`;
            form.setValue('date_description', description, { shouldDirty: false });
          } else if (currentCategory === 'PE3 Dates') {
            // For PE3 Dates, update description if time is also set
            const currentTimeValue = form.getValues('time_value');
            if (currentTimeValue) {
              const autoDescription = formatPE3Description(updatedDate, currentTimeValue);
              const currentDescription = form.getValues('date_description');
              if (autoDescription && (!currentDescription || isAutoGeneratedDescription(currentDescription))) {
                form.setValue('date_description', autoDescription, { shouldDirty: false });
              }
            }
          }

          // For ÖMC Dates, update the description
          if (currentCategory === 'ÖMC Dates') {
            const description = formatOMCDateDescription(updatedDate);
            if (description) {
              form.setValue('date_description', description, { shouldDirty: false });
            }
          }
        }
      } catch (error) {
        // Silently fail if date parsing fails
        console.error('Error updating date for year change:', error);
      }
    }

    // Update previous year
    prevValuesRef.current.year = currentYear;
  }, [year, dateValue, isOpen, form]);

  useEffect(() => {
    if (!isOpen) {
      // Reset previous values when modal closes
      prevValuesRef.current = { category: '', dateValue: '', timeValue: '', year: 0 };
      return;
    }

    // Initialize previous values on modal open
    const initialCategory = form.getValues('category');
    const initialDateValue = form.getValues('date_value');
    const initialTimeValue = form.getValues('time_value');
    const initialYear = form.getValues('year');
    prevValuesRef.current = {
      category: initialCategory || '',
      dateValue: initialDateValue || '',
      timeValue: initialTimeValue || '',
      year: initialYear || new Date().getFullYear(),
    };

    const checkAndUpdateDescription = () => {
      // Always get current values directly from form (works in both production and tests)
      const currentCategory = form.getValues('category');
      const currentDateValue = form.getValues('date_value');
      const currentTimeValue = form.getValues('time_value');
      const currentDescription = form.getValues('date_description');

      // Check if values have changed
      const valuesChanged = 
        prevValuesRef.current.category !== (currentCategory || '') ||
        prevValuesRef.current.dateValue !== (currentDateValue || '') ||
        prevValuesRef.current.timeValue !== (currentTimeValue || '');

      if (valuesChanged && currentCategory === 'PE3 Dates' && currentDateValue && currentTimeValue) {
        const autoDescription = formatPE3Description(currentDateValue, currentTimeValue);
        
        if (autoDescription && isAutoGeneratedDescription(currentDescription)) {
          form.setValue('date_description', autoDescription, { shouldDirty: false });
        }
      }

      // Update ref for next comparison
      prevValuesRef.current = {
        category: currentCategory || '',
        dateValue: currentDateValue || '',
        timeValue: currentTimeValue || '',
        year: prevValuesRef.current.year, // Keep year from previous effect
      };
    };

    // Check immediately
    checkAndUpdateDescription();

    // Poll periodically when modal is open (ensures updates even when watch() doesn't fire in tests)
    // Polling interval of 150ms provides good balance between responsiveness and performance
    const intervalId = setInterval(checkAndUpdateDescription, 150);

    return () => clearInterval(intervalId);
  // Only depend on isOpen - polling handles value changes
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  // Auto-calculate deadlines for PE3 dates when date_value is set
  useEffect(() => {
    if (!isOpen) return;

    const currentCategory = form.getValues('category');
    const currentDateValue = form.getValues('date_value');
    const currentDeadlineSubmit = form.getValues('deadline_submit');
    const currentDeadlineCancel = form.getValues('deadline_cancel');

    // Auto-calculate if:
    // 1. Category is PE3 Dates
    // 2. Date value is set
    // 3. Deadlines are not already manually set (allow override)
    if (
      currentCategory === 'PE3 Dates' &&
      currentDateValue &&
      !currentDeadlineSubmit &&
      !currentDeadlineCancel
    ) {
      try {
        // Calculate deadlines using the same logic as import
        // Pass single date as array to reuse existing function
        const calculation = calculatePE3Deadlines([currentDateValue]);
        
        // Auto-populate deadline fields
        form.setValue('deadline_submit', calculation.deadlineSubmit, { shouldDirty: false });
        form.setValue('deadline_cancel', calculation.deadlineCancel, { shouldDirty: false });
      } catch (error) {
        // Silently fail if calculation fails (invalid date, etc.)
        console.error('Error calculating PE3 deadlines:', error);
      }
    }
  }, [category, dateValue, isOpen, form]);

  const onSubmit = async (data: CreateImportantDateInput) => {
    try {
      setIsSubmitting(true);
      
      // Normalize optional fields to ensure null instead of undefined
      const normalizedData = {
        ...data,
        time_value: data.time_value ?? null,
        deadline_submit: data.deadline_submit ?? null,
        deadline_cancel: data.deadline_cancel ?? null,
      };
      
      const newDate = await importantDateService.create(normalizedData);
      
      toast.success(t('addImportantDate.dateCreated'));
      
      form.reset();
      onSuccess();
      onClose();
    } catch (error) {
      // Handle validation errors with details
      if (
        error instanceof Error &&
        "details" in error &&
        typeof (error as Error & { details?: Record<string, string[]> })
          .details === "object"
      ) {
        const details = (
          error as Error & { details?: Record<string, string[]> }
        ).details;
        if (details) {
          Object.entries(details).forEach(([field, messages]) => {
            form.setError(field as keyof CreateImportantDateInput, {
              message: messages[0],
            });
          });
        }
      }
      // Generic error
      else {
        toast.error(t('createFailed'), {
          description:
            error instanceof Error ? error.message : "Unknown error occurred",
        });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleOpenChange = (open: boolean) => {
    if (!open && !isSubmitting) {
      form.reset({
        week_number: null,
        year: new Date().getFullYear(),
        category: "Stena Dates",
        date_description: "",
        date_value: "",
        time_value: null,
        deadline_submit: null,
        deadline_cancel: null,
        notes: null,
      });
      onClose();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Lägg till viktigt datum</DialogTitle>
          <DialogDescription>
            Skapa en ny viktig datumpost för operativ planering.
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              {/* Category */}
              <FormField
                control={form.control}
                name="category"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      Kategori <span className="text-red-500">*</span>
                    </FormLabel>
                    <Select
                      onValueChange={(value) => {
                        field.onChange(value);
                        // Trigger auto-population if switching to PE3 Dates and date/time are already set
                        // Use setTimeout to ensure form state is updated
                        if (value === 'PE3 Dates') {
                          setTimeout(() => {
                            const currentDateValue = form.getValues('date_value');
                            const currentTimeValue = form.getValues('time_value');
                            if (currentDateValue && currentTimeValue) {
                              const autoDescription = formatPE3Description(currentDateValue, currentTimeValue);
                              if (autoDescription && isAutoGeneratedDescription(form.getValues('date_description'))) {
                                form.setValue('date_description', autoDescription, { shouldDirty: false });
                              }
                            }
                          }, 0);
                        }
                      }}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Välj kategori" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="Stena Dates">Stena Dates</SelectItem>
                        <SelectItem value="ÖMC Dates">ÖMC Dates</SelectItem>
                        <SelectItem value="PE3 Dates">PE3 Dates</SelectItem>
                        <SelectItem value="Other">Övrigt</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Date Value - conditional rendering based on category */}
              <FormField
                control={form.control}
                name="date_value"
                render={({ field }) => {
                  const category = form.watch('category');
                  const isOMC = category === 'ÖMC Dates';
                  
                  return (
                    <FormItem className={isOMC ? "col-span-2" : ""}>
                      <FormLabel>
                        Datumvärde <span className="text-red-500">*</span>
                      </FormLabel>
                      <FormControl>
                        {isOMC ? (
                          <OMCDatePicker
                            value={field.value || ""}
                            onChange={(value) => {
                              field.onChange(value);
                              // Auto-calculate week number when date is selected
                              const weekNum = getWeekNumberFromDateString(value);
                              if (weekNum !== null && !form.getValues('week_number')) {
                                form.setValue('week_number', weekNum);
                              }
                              // Auto-populate date description for ÖMC dates
                              if (value) {
                                const description = formatOMCDateDescription(value);
                                if (description) {
                                  form.setValue('date_description', description);
                                }
                              }
                            }}
                          />
                        ) : (
                          <Input 
                            type="date"
                            {...field}
                            onChange={(e) => {
                              field.onChange(e.target.value);
                              // Auto-calculate week number when date is selected
                              const weekNum = getWeekNumberFromDateString(e.target.value);
                              if (weekNum !== null && !form.getValues('week_number')) {
                                form.setValue('week_number', weekNum);
                              }
                              // Auto-populate date description with weekday and day/month
                              // Skip for PE3 Dates - handled by auto-population function
                              const currentCategory = form.getValues('category');
                              if (e.target.value && currentCategory !== 'PE3 Dates') {
                                const date = new Date(e.target.value + 'T00:00:00');
                                const weekdays = ['Söndag', 'Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag'];
                                const weekday = weekdays[date.getDay()];
                                const day = date.getDate();
                                const month = date.getMonth() + 1;
                                const description = `${weekday} ${day}/${month}`;
                                form.setValue('date_description', description);
                              } else if (e.target.value && currentCategory === 'PE3 Dates') {
                                // For PE3 Dates, trigger auto-population if time is also set
                                // Use setTimeout to ensure form state is updated
                                setTimeout(() => {
                                  const currentTimeValue = form.getValues('time_value');
                                  const currentDescription = form.getValues('date_description');
                                  if (currentTimeValue) {
                                    const autoDescription = formatPE3Description(e.target.value, currentTimeValue);
                                    // Always update if description is empty or matches auto-generated pattern
                                    if (autoDescription && (!currentDescription || isAutoGeneratedDescription(currentDescription))) {
                                      form.setValue('date_description', autoDescription, { shouldDirty: false });
                                    }
                                  }
                                }, 0);
                              }
                            }}
                          />
                        )}
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  );
                }}
              />

              {/* Week Number */}
              <FormField
                control={form.control}
                name="week_number"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Veckonummer</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        min="1"
                        max="53"
                        placeholder="t.ex., 7"
                        {...field}
                        value={field.value ?? ""}
                        onChange={(e) => {
                          const value = e.target.value;
                          field.onChange(value === "" ? null : parseInt(value, 10));
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Year */}
              <FormField
                control={form.control}
                name="year"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      År <span className="text-red-500">*</span>
                    </FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        min="2020"
                        max="2100"
                        {...field}
                        value={field.value ?? ''}
                        onChange={(e) => {
                          const value = e.target.value;
                          // Only update if value is valid number
                          if (value === '' || isNaN(parseInt(value, 10))) {
                            return; // Don't update if empty or invalid
                          }
                          field.onChange(parseInt(value, 10));
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Time Value - only for PE3 Dates */}
              {form.watch('category') === 'PE3 Dates' && (
                <FormField
                  control={form.control}
                  name="time_value"
                  render={({ field }) => (
                    <FormItem className="col-span-2">
                      <FormLabel>
                        Tid <span className="text-red-500">*</span>
                      </FormLabel>
                      <FormControl>
                        <TimePicker
                          value={field.value ?? null}
                          onChange={(value) => {
                            field.onChange(value);
                            // Trigger auto-population for PE3 dates when time is set
                            // Use setTimeout to ensure form state is updated
                            setTimeout(() => {
                              const currentCategory = form.getValues('category');
                              const currentDateValue = form.getValues('date_value');
                              const currentDescription = form.getValues('date_description');
                              if (currentCategory === 'PE3 Dates' && currentDateValue && value) {
                                const autoDescription = formatPE3Description(currentDateValue, value);
                                // Always update if description is empty or matches auto-generated pattern
                                if (autoDescription && (!currentDescription || isAutoGeneratedDescription(currentDescription))) {
                                  form.setValue('date_description', autoDescription, { shouldDirty: false });
                                }
                              }
                            }, 0);
                          }}
                          placeholder="HH:MM (t.ex. 14:30)"
                        />
                      </FormControl>
                      <p className="text-sm text-muted-foreground">
                        Tid är obligatorisk för PE3-datum
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {/* Deadline Submit - only for PE3 Dates */}
              {form.watch('category') === 'PE3 Dates' && (
                <FormField
                  control={form.control}
                  name="deadline_submit"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>
                        Inlämningsdeadline (Valfritt)
                      </FormLabel>
                      <FormControl>
                        <Input
                          type="date"
                          {...field}
                          value={field.value ?? ""}
                          onChange={(e) => {
                            const value = e.target.value;
                            field.onChange(value === "" ? null : value);
                          }}
                        />
                      </FormControl>
                      <p className="text-xs text-muted-foreground">
                        Efter detta datum kan inga nya medarbetare tilldelas
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {/* Deadline Cancel - only for PE3 Dates */}
              {form.watch('category') === 'PE3 Dates' && (
                <FormField
                  control={form.control}
                  name="deadline_cancel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>
                        Avbokningsdeadline (Valfritt)
                      </FormLabel>
                      <FormControl>
                        <Input
                          type="date"
                          {...field}
                          value={field.value ?? ""}
                          onChange={(e) => {
                            const value = e.target.value;
                            field.onChange(value === "" ? null : value);
                          }}
                        />
                      </FormControl>
                      <p className="text-xs text-muted-foreground">
                        Efter detta datum kan tilldelningar inte avbokas
                      </p>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {/* Date Description - now optional and auto-populated */}
              <FormField
                control={form.control}
                name="date_description"
                render={({ field }) => (
                  <FormItem className="col-span-2">
                    <FormLabel>
                      Datumbeskrivning
                    </FormLabel>
                    <FormControl>
                      <Input placeholder="t.ex., Fredag 14/2" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Notes */}
            <FormField
              control={form.control}
              name="notes"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Anteckningar (Valfritt)</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Ytterligare anteckningar eller detaljer..."
                      {...field}
                      value={field.value ?? ""}
                      onChange={(e) => {
                        const value = e.target.value;
                        field.onChange(value === "" ? null : value);
                      }}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleOpenChange(false)}
                disabled={isSubmitting}
              >
                {tCommon('cancel')}
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Skapar...' : 'Skapa'}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
